version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "3000:3000"